pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
        DOCKER_IMAGE = "AymanMakram/messaging_app"
        VENV_DIR = "venv"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: "main",
                    url: 'https://github.com/AymanMakram/alx-backend-python.git',
                    credentialsId: 'dg-github-creds-id'
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                python3 --version
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests with Pytest') {
            steps {
                sh '''
                . ${VENV_DIR}/bin/activate
                mkdir -p reports
                pytest messaging_app/tests \
                  --junitxml=reports/test-results.xml
                '''
            }
        }

        stage('Verify Docker Connection') {
            steps {
                sh '''
                docker info
                docker version
                '''
            }
        }

        stage('Build Production Docker Image') {
            steps {
                sh '''
                docker build -t $DOCKER_IMAGE:latest \
                  -f messaging_app/Dockerfile messaging_app
                '''
            }
        }

        stage('Push Production Docker Image') {
            steps {
                sh '''
                mkdir -p /tmp/docker-config
                echo $DOCKERHUB_CREDENTIALS_PSW | docker \
                  --config /tmp/docker-config login \
                  -u $DOCKERHUB_CREDENTIALS_USR --password-stdin

                docker --config /tmp/docker-config push $DOCKER_IMAGE:latest
                '''
            }
        }
    }

    post {
        always {
            junit 'reports/test-results.xml'
            archiveArtifacts artifacts: 'reports/test-results.xml', fingerprint: true
        }
        success {
            echo '✅ Tests passed and image pushed successfully!'
        }
        failure {
            echo '❌ Tests failed. Check pytest report.'
        }
    }
}
